# Generated by Django 4.0 on 2022-02-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ass', '0003_quesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ass.user'),
            preserve_default=False,
        ),
    ]
