# Generated by Django 4.0 on 2022-02-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ass', '0004_quesmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='user',
        ),
    ]
